"""Decide whether a phase needs cloud GPU compute, and provision/teardown if so.

Flow per phase:
  1. ``needs_gpu(sub_spec)`` — cheap LLM call against the sub-spec markdown.
     Cached by phase_id so retries don't re-decide.
  2. If yes, ``provision(sub_spec, work_dir)``:
       - check the per-run BudgetLedger; if reservation would exceed the cap,
         bubble to the orchestrator's approval_callback (typically a click
         prompt) to ask the operator to raise the cap
       - generate ephemeral ed25519 keypair under work_dir/.cloud
       - register key with Lambda Cloud API
       - launch instance, wait until ready
       - drop work_dir/.cloud/env and work_dir/remote_run.sh
       - return ComputeHandle (whose ``teardown()`` terminates the instance
         and releases the budget entry)
  3. The execution loop runs the sub-agent normally. The sub-agent's prompt
     is augmented to know about remote_run.sh and the request_compute tool.
  4. Mid-phase the sub-agent can call ``upgrade(handle, ...)`` (via the
     request_compute MCP tool) to swap in a bigger box or extend hours; the
     same budget gate applies.
  5. ``ComputeHandle.teardown()`` is called from the loop's finally block.
"""

from __future__ import annotations

import json
import logging
import os
import re
import threading
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Any, Awaitable, Callable

from claude_agent_sdk import (
    AssistantMessage,
    ClaudeAgentOptions,
    TextBlock,
    query,
)

from ..config import Config
from ..events.emitter import EventEmitter
from ..models.context import SubSpec
from .budget import FALLBACK_HOURLY_RATE_USD, BudgetLedger
from .lambda_cloud import (
    LambdaClient,
    LambdaInstance,
    generate_ssh_keypair,
)

logger = logging.getLogger(__name__)


# Defaults — overridable via env vars so users can swap GPU class without code edits.
DEFAULT_INSTANCE_TYPE = os.environ.get("LAMBDA_INSTANCE_TYPE", "gpu_1x_a10")
DEFAULT_REGION = os.environ.get("LAMBDA_REGION", "us-east-1")
# Estimated runtime hours used for cost projection. Conservative — actual
# elapsed time replaces this on teardown via BudgetLedger.release.
DEFAULT_ESTIMATED_HOURS = float(os.environ.get("LAMBDA_ESTIMATED_HOURS", "2"))


@dataclass
class CloudDecision:
    needs_gpu: bool
    instance_type: str
    rationale: str


@dataclass
class ApprovalRequest:
    """Bubbled to the operator when a provision/upgrade would exceed the cap.

    The approval_callback receives this and must return:
      - the new cap_usd to set (>= current cap) if approved
      - None to deny — provisioner will skip the GPU (or fail the upgrade)
    """
    phase_id: str
    instance_type: str
    requested_cost_usd: float  # estimated cost of this single reservation
    current_total_usd: float
    cap_usd: float
    is_upgrade: bool
    reason: str  # human-readable rationale (sub-agent's reason for upgrade, or "initial provision")


@dataclass
class ComputeHandle:
    machine: LambdaInstance
    work_dir: Path
    _client: LambdaClient
    _provisioner: "CloudProvisioner"
    _ledger_entry_id: str
    _terminated: bool = False

    async def teardown(self) -> None:
        """Terminate the instance and release its budget entry. Idempotent."""
        if self._terminated:
            return
        self._terminated = True
        try:
            await self._client.terminate_instance(self.machine.id)
        finally:
            self._provisioner._ledger.release(self._ledger_entry_id)
            self._provisioner._on_terminated(self)
            await self._client.aclose()


_REMOTE_RUN_SH = r"""#!/usr/bin/env bash
# Auto-generated by research-builder. Runs a command on the provisioned
# Lambda Cloud GPU instance: rsyncs the local work_dir up, executes remotely,
# rsyncs results back. Usage: bash remote_run.sh "python train.py --epochs 1"
set -euo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"
source "$HERE/.cloud/env"
KEY="$HERE/.cloud/id_ed25519"
SSH_OPTS=(-i "$KEY" -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null)
RSYNC_SSH="ssh ${SSH_OPTS[*]}"

rsync -az --delete \
  --exclude .cloud --exclude '__pycache__' --exclude '*.pyc' --exclude '.git' \
  -e "$RSYNC_SSH" \
  "$HERE/" "$REMOTE_USER@$REMOTE_HOST:$REMOTE_WORKDIR/"

ssh "${SSH_OPTS[@]}" "$REMOTE_USER@$REMOTE_HOST" "cd $REMOTE_WORKDIR && $*"
RC=$?

rsync -az \
  --exclude .cloud \
  -e "$RSYNC_SSH" \
  "$REMOTE_USER@$REMOTE_HOST:$REMOTE_WORKDIR/" "$HERE/"

exit $RC
"""


# Approval callback: takes an ApprovalRequest, returns the new cap (>= current)
# if approved, or None to deny. Async so it can shell out to a TUI prompt.
ApprovalCallback = Callable[[ApprovalRequest], Awaitable[float | None]]


class CloudProvisioner:
    """Owns the LLM gate, budget ledger, and machine lifecycle for cloud-backed phases."""

    def __init__(
        self,
        config: Config,
        api_key: str,
        ledger: BudgetLedger,
        approval_callback: ApprovalCallback,
        emitter: EventEmitter | None = None,
        persistence_path: Path | None = None,
    ) -> None:
        self.config = config
        self._api_key = api_key
        self._ledger = ledger
        self._approval_callback = approval_callback
        self._decision_cache: dict[str, CloudDecision] = {}
        # Memoize Lambda's pricing table — small, never changes mid-run.
        self._price_cache: dict[str, float | None] = {}
        # Lifecycle event sink + on-disk snapshot. Both optional — the
        # provisioner runs headless without either, but the webapp's
        # Compute tab needs the snapshot to list past instances after a
        # restart and the emitter to stream live state.
        self._emitter = emitter
        self._persistence_path = (
            Path(persistence_path) if persistence_path is not None else None
        )
        # Single-writer guard for the JSON snapshot. The provisioner is
        # invoked from the asyncio loop in one process, but teardown can
        # run during shutdown signal handling — keep it sync-safe.
        self._persist_lock = threading.Lock()
        # Loaded once on construction so we don't clobber records from
        # a prior process (resumed runs).
        self._snapshot: dict[str, Any] = self._load_snapshot()

    @property
    def ledger(self) -> BudgetLedger:
        return self._ledger

    # ---- pricing ------------------------------------------------------------

    async def _hourly_rate(self, instance_type: str) -> float:
        """Look up an instance's hourly rate, falling back to a conservative default."""
        if instance_type in self._price_cache:
            cached = self._price_cache[instance_type]
            return cached if cached is not None else FALLBACK_HOURLY_RATE_USD
        client = LambdaClient(self._api_key)
        try:
            rate = await client.get_instance_type_price(instance_type)
        finally:
            await client.aclose()
        self._price_cache[instance_type] = rate
        if rate is None:
            logger.warning(
                "CloudProvisioner: pricing unavailable for %s; using fallback $%.2f/hr",
                instance_type, FALLBACK_HOURLY_RATE_USD,
            )
            return FALLBACK_HOURLY_RATE_USD
        return rate

    # ---- gate ---------------------------------------------------------------

    async def needs_gpu(
        self,
        sub_spec: SubSpec,
        full_spec_markdown: str | None = None,
    ) -> CloudDecision:
        """Classify whether one phase needs a GPU.

        ``full_spec_markdown`` is the entire canonical spec.md. Pass it whenever
        possible — without it, the classifier only sees the per-phase slice,
        which is wrong for phases like eval whose own spec describes "compute
        BLEU" without naming the model. With the full spec the classifier can
        cross-reference the architecture section and correctly flag inference
        on a large model as needing a GPU.
        """
        phase_id = sub_spec.phase.phase_id
        cached = self._decision_cache.get(phase_id)
        if cached is not None:
            logger.debug("CloudProvisioner: cached decision for phase=%s: %s", phase_id, cached.needs_gpu)
            return cached

        # Pull architecture-relevant context from the full spec so the
        # classifier can reason about the model size when the per-phase slice
        # doesn't mention it (typical for eval / inference phases).
        full_spec_block = ""
        if full_spec_markdown:
            full_spec_block = (
                "\nFull canonical spec (truncated, for cross-phase context — use this "
                "to find the model architecture / parameter count when judging eval "
                "and inference phases):\n"
                "----\n"
                f"{full_spec_markdown[:8000]}\n"
                "----\n"
            )

        prompt = (
            "You are a routing classifier for a research-paper reproduction harness.\n\n"
            "Given the spec for one phase, decide whether executing it would benefit "
            "from a cloud GPU machine. GPU is warranted for:\n"
            "  - ANY model training, fine-tuning, gradient-based optimization, or "
            "fitting of learned parameters — regardless of model size. This includes "
            "small MLPs, linear models with SGD, and short smoke runs. The harness "
            "must never run training locally; when in doubt about a training phase, "
            "choose GPU.\n"
            "  - GPU-accelerated inference / eval whenever the model being evaluated "
            "is large enough that CPU inference would be impractically slow "
            "(transformers, CNNs, deep nets with >10M params, any LLM, beam search "
            "decoding over a learned model, etc.) — even if the per-phase spec only "
            "says 'compute metric X', cross-reference the architecture section of "
            "the full spec to judge model size\n"
            "  - any phase whose runtime would be hours on CPU but minutes on GPU\n\n"
            "GPU is NOT warranted for: data download, CPU preprocessing, spec "
            "authoring, report writing, or INFERENCE/eval of trivial models "
            "(simple regression, small MLPs, lookup tables). The trivial-model "
            "carve-out applies ONLY to inference — training of a trivial model "
            "still gets a GPU.\n\n"
            "Respond with a single JSON object on one line, no prose, no code fences:\n"
            '{"needs_gpu": <bool>, "instance_type": "<Lambda Cloud instance type, e.g. '
            'gpu_1x_a10, gpu_1x_a100, gpu_8x_a100, gpu_1x_h100>", '
            '"rationale": "<one short sentence — for eval/inference phases mention the '
            'model size you found in the architecture section>"}\n\n'
            f"Phase id: {phase_id}\n"
            f"Phase title: {sub_spec.phase.title}\n\n"
            "Phase spec markdown (truncated):\n"
            "----\n"
            f"{sub_spec.spec_markdown[:4000]}\n"
            "----\n"
            f"{full_spec_block}"
        )

        options = ClaudeAgentOptions(
            system_prompt="You are a terse classifier. Always reply with one JSON object.",
            allowed_tools=[],
            permission_mode="bypassPermissions",
            model=self.config.model,
            max_turns=1,
        )

        text_chunks: list[str] = []
        try:
            async for message in query(prompt=prompt, options=options):
                if isinstance(message, AssistantMessage):
                    for block in message.content:
                        if isinstance(block, TextBlock):
                            text_chunks.append(block.text)
        except Exception:
            logger.exception("CloudProvisioner: needs_gpu LLM call failed; defaulting to no GPU")
            decision = CloudDecision(False, DEFAULT_INSTANCE_TYPE, "LLM call failed; defaulting to local")
            self._decision_cache[phase_id] = decision
            return decision

        raw = "".join(text_chunks).strip()
        decision = _parse_decision(raw)
        logger.info(
            "CloudProvisioner: phase=%s needs_gpu=%s instance_type=%s rationale=%s",
            phase_id, decision.needs_gpu, decision.instance_type, decision.rationale,
        )
        self._decision_cache[phase_id] = decision
        return decision

    # ---- upfront estimate ---------------------------------------------------

    async def estimate_run(
        self,
        sub_specs: list[SubSpec],
        full_spec_markdown: str | None = None,
    ) -> "RunEstimate":
        """Classify every phase up front and total the projected GPU spend.

        Caches each phase's CloudDecision so the lazy provision path doesn't
        re-LLM. Returns an aggregate the loop can surface to the operator
        (and use to ask up-front whether to raise the cap).

        Pass ``full_spec_markdown`` so the classifier can cross-reference the
        architecture section when judging eval/inference phases — without it,
        eval almost always under-classifies as CPU-only.
        """
        per_phase: list[PhaseEstimate] = []
        total = 0.0
        for sub_spec in sub_specs:
            decision = await self.needs_gpu(sub_spec, full_spec_markdown=full_spec_markdown)
            if not decision.needs_gpu:
                per_phase.append(PhaseEstimate(
                    phase_id=sub_spec.phase.phase_id,
                    needs_gpu=False, instance_type="", hourly_rate_usd=0.0,
                    estimated_hours=0.0, estimated_cost_usd=0.0,
                ))
                continue
            instance_type = decision.instance_type or DEFAULT_INSTANCE_TYPE
            rate = await self._hourly_rate(instance_type)
            cost = rate * DEFAULT_ESTIMATED_HOURS
            total += cost
            per_phase.append(PhaseEstimate(
                phase_id=sub_spec.phase.phase_id,
                needs_gpu=True,
                instance_type=instance_type,
                hourly_rate_usd=rate,
                estimated_hours=DEFAULT_ESTIMATED_HOURS,
                estimated_cost_usd=cost,
            ))
        return RunEstimate(per_phase=per_phase, total_usd=total, cap_usd=self._ledger.cap_usd)

    # ---- provisioning -------------------------------------------------------

    async def provision(
        self,
        sub_spec: SubSpec,
        work_dir: Path,
        full_spec_markdown: str | None = None,
    ) -> ComputeHandle | None:
        # In the normal flow the loop calls ``estimate_run`` first, which
        # populates the per-phase decision cache. ``full_spec_markdown`` is
        # only consulted on a cache miss, so it's safe (and cheap) to pass
        # at this site as a fallback.
        decision = await self.needs_gpu(sub_spec, full_spec_markdown=full_spec_markdown)
        if not decision.needs_gpu:
            return None

        instance_type = decision.instance_type or DEFAULT_INSTANCE_TYPE
        rate = await self._hourly_rate(instance_type)
        est_cost = rate * DEFAULT_ESTIMATED_HOURS

        # Hard budget gate. Bubble to operator if this reservation would exceed cap.
        if self._ledger.would_exceed(est_cost):
            req = ApprovalRequest(
                phase_id=sub_spec.phase.phase_id,
                instance_type=instance_type,
                requested_cost_usd=est_cost,
                current_total_usd=self._ledger.projected_total(),
                cap_usd=self._ledger.cap_usd,
                is_upgrade=False,
                reason=f"Initial GPU provision for phase '{sub_spec.phase.phase_id}'",
            )
            new_cap = await self._approval_callback(req)
            if new_cap is None:
                logger.info(
                    "CloudProvisioner: operator declined GPU for phase=%s (would exceed cap)",
                    sub_spec.phase.phase_id,
                )
                return None
            self._ledger.raise_cap(new_cap)

        # Reserve budget BEFORE launching so concurrent requests can't double-spend.
        entry_id = self._ledger.commit(
            phase_id=sub_spec.phase.phase_id,
            instance_type=instance_type,
            hourly_rate_usd=rate,
            estimated_hours=DEFAULT_ESTIMATED_HOURS,
        )

        try:
            handle = await self._launch(
                phase_id=sub_spec.phase.phase_id,
                instance_type=instance_type,
                work_dir=work_dir,
                ledger_entry_id=entry_id,
            )
        except Exception:
            # Provision failed — refund the budget entry so we don't bill for nothing.
            self._ledger.release(entry_id)
            raise

        logger.info(
            "CloudProvisioner: provisioned phase=%s instance=%s ip=%s ledger=%s",
            sub_spec.phase.phase_id, handle.machine.id, handle.machine.public_ip,
            self._ledger.summary(),
        )
        return handle

    # ---- mid-phase upgrade --------------------------------------------------

    async def upgrade(
        self,
        handle: ComputeHandle,
        *,
        new_instance_type: str | None = None,
        additional_hours: float | None = None,
        reason: str = "",
    ) -> tuple[bool, str]:
        """Swap the running instance for a bigger one and/or extend the hours reservation.

        Returns (success, message). On success, ``handle.machine`` and the
        on-disk ``.cloud/env`` are updated in place; the sub-agent re-invokes
        ``bash remote_run.sh`` to pick up the new box. On budget refusal,
        returns (False, explanation).
        """
        if new_instance_type is None and additional_hours is None:
            return False, "Must specify at least one of new_instance_type, additional_hours."

        # Pull the current entry so we can compute the delta.
        current_entry = self._ledger._entries.get(handle._ledger_entry_id)
        if current_entry is None:
            return False, "Internal error: current budget entry missing."

        target_instance_type = new_instance_type or current_entry.instance_type
        target_hours = (current_entry.estimated_hours + additional_hours) if additional_hours else current_entry.estimated_hours
        target_rate = await self._hourly_rate(target_instance_type)
        target_cost = target_rate * target_hours

        # Release the OLD entry first so its actual elapsed cost replaces its
        # estimate in the projected total — that frees up headroom before we
        # check whether the upgrade fits.
        self._ledger.release(handle._ledger_entry_id)

        if self._ledger.would_exceed(target_cost):
            req = ApprovalRequest(
                phase_id=current_entry.phase_id,
                instance_type=target_instance_type,
                requested_cost_usd=target_cost,
                current_total_usd=self._ledger.projected_total(),
                cap_usd=self._ledger.cap_usd,
                is_upgrade=True,
                reason=reason or f"Sub-agent upgrade request from {current_entry.instance_type} to {target_instance_type}",
            )
            new_cap = await self._approval_callback(req)
            if new_cap is None:
                # Re-commit a synthetic entry covering the elapsed time we just
                # released — but it's already been billed (via release), so
                # that's accurate. We just refuse the upgrade.
                return False, (
                    f"Upgrade denied: would cost ${target_cost:.2f}, projected total "
                    f"${self._ledger.projected_total() + target_cost:.2f} exceeds cap "
                    f"${self._ledger.cap_usd:.2f} and operator declined to raise it."
                )
            self._ledger.raise_cap(new_cap)

        # Reserve the new entry, tear down old machine, launch new.
        new_entry_id = self._ledger.commit(
            phase_id=current_entry.phase_id,
            instance_type=target_instance_type,
            hourly_rate_usd=target_rate,
            estimated_hours=target_hours,
        )

        # Tear down the old machine.
        try:
            await self._client_for(handle).terminate_instance(handle.machine.id)
        except Exception:
            logger.exception("Failed to terminate old machine during upgrade; continuing")

        # Launch the new one in place of the old. Reuse the work_dir; rewrite .cloud/env.
        try:
            new_handle = await self._launch(
                phase_id=current_entry.phase_id,
                instance_type=target_instance_type,
                work_dir=handle.work_dir,
                ledger_entry_id=new_entry_id,
            )
        except Exception:
            self._ledger.release(new_entry_id)
            raise

        # Snapshot the old instance ID before we mutate the handle so the
        # snapshot record can be marked terminated.
        old_instance_id = handle.machine.id

        # Mutate the existing handle so the orchestrator's finally block tears down the new box.
        handle.machine = new_handle.machine
        handle._client = new_handle._client
        handle._ledger_entry_id = new_entry_id
        handle._terminated = False

        # _launch already wrote the new instance as a fresh provisioned
        # record. Convert that into an upgrade record so the snapshot's
        # history tracks the swap rather than showing two unrelated boxes.
        self._on_upgraded(
            old_instance_id, handle,
            phase_id=current_entry.phase_id,
            reason=reason or "sub-agent upgrade",
        )

        msg = (
            f"Upgraded to {target_instance_type} (~${target_rate:.2f}/hr × {target_hours:.1f}hrs "
            f"= ${target_cost:.2f}). New IP: {handle.machine.public_ip}. "
            f"Re-invoke `bash remote_run.sh \"...\"` — the wrapper will rsync to the new box."
        )
        logger.info("CloudProvisioner: %s", msg)
        return True, msg

    # ---- internal -----------------------------------------------------------

    async def _launch(
        self,
        *,
        phase_id: str,
        instance_type: str,
        work_dir: Path,
        ledger_entry_id: str,
    ) -> ComputeHandle:
        cloud_dir = work_dir / ".cloud"
        priv_key, pub_key = generate_ssh_keypair(cloud_dir)

        client = LambdaClient(self._api_key)
        try:
            key_name = f"rb-{phase_id}-{os.getpid()}-{ledger_entry_id}"
            await client.add_ssh_key(key_name, pub_key)
            instance = await client.launch_instance(
                instance_type=instance_type,
                ssh_key_names=[key_name],
                name=f"rb-{phase_id}-{os.getpid()}-{ledger_entry_id}",
                region=DEFAULT_REGION,
            )
            ready = await client.wait_until_ready(instance.id)
            instance.public_ip = str(ready.get("ip") or instance.public_ip)
            instance.state = str(ready.get("status", instance.state))
            instance.ssh_key_path = priv_key
        except Exception:
            logger.exception("CloudProvisioner._launch: failed; cleaning up client")
            await client.aclose()
            raise

        # Drop env + helper script into work_dir
        env_file = cloud_dir / "env"
        env_file.write_text(
            f'REMOTE_HOST="{instance.public_ip}"\n'
            f'REMOTE_USER="{instance.ssh_user}"\n'
            f'REMOTE_WORKDIR="/home/{instance.ssh_user}/work"\n'
        )
        helper = work_dir / "remote_run.sh"
        helper.write_text(_REMOTE_RUN_SH)
        helper.chmod(0o755)

        handle = ComputeHandle(
            machine=instance,
            work_dir=work_dir,
            _client=client,
            _provisioner=self,
            _ledger_entry_id=ledger_entry_id,
        )
        self._on_provisioned(handle, phase_id=phase_id)
        return handle

    def _client_for(self, handle: ComputeHandle) -> LambdaClient:
        return handle._client

    # ---- snapshot + event emission --------------------------------------

    def _load_snapshot(self) -> dict[str, Any]:
        if self._persistence_path is None:
            return {"instances": {}}
        try:
            raw = self._persistence_path.read_text()
        except FileNotFoundError:
            return {"instances": {}}
        except OSError as e:
            logger.warning("CloudProvisioner: could not read %s: %s", self._persistence_path, e)
            return {"instances": {}}
        try:
            data = json.loads(raw or "{}")
        except json.JSONDecodeError as e:
            logger.warning("CloudProvisioner: corrupt snapshot at %s: %s", self._persistence_path, e)
            return {"instances": {}}
        if "instances" not in data or not isinstance(data["instances"], dict):
            data["instances"] = {}
        return data

    def _persist_snapshot(self) -> None:
        if self._persistence_path is None:
            return
        path = self._persistence_path
        with self._persist_lock:
            try:
                path.parent.mkdir(parents=True, exist_ok=True)
                payload = {
                    "instances": self._snapshot.get("instances", {}),
                    "budget": {
                        "cap_usd": self._ledger.cap_usd,
                        "projected_total_usd": self._ledger.projected_total(),
                    },
                    "updated_at": datetime.now().isoformat(timespec="seconds"),
                }
                tmp = path.with_suffix(path.suffix + ".tmp")
                tmp.write_text(json.dumps(payload, indent=2, default=str))
                tmp.replace(path)
            except OSError as e:
                logger.warning("CloudProvisioner: could not write %s: %s", path, e)

    def _instance_record(
        self,
        handle: ComputeHandle,
        *,
        phase_id: str,
        status: str,
        provisioned_at: str | None = None,
    ) -> dict[str, Any]:
        entry = self._ledger._entries.get(handle._ledger_entry_id)
        rate = entry.hourly_rate_usd if entry else 0.0
        est_hours = entry.estimated_hours if entry else 0.0
        return {
            "instance_id": handle.machine.id,
            "phase_id": phase_id,
            "instance_type": handle.machine.instance_type,
            "public_ip": handle.machine.public_ip,
            "ssh_user": handle.machine.ssh_user,
            "ssh_key_path": str(handle.machine.ssh_key_path),
            "region": DEFAULT_REGION,
            "hourly_rate_usd": rate,
            "estimated_hours": est_hours,
            "estimated_cost_usd": rate * est_hours,
            "actual_hours": None,
            "actual_cost_usd": None,
            "status": status,
            "provisioned_at": provisioned_at or datetime.now().isoformat(timespec="seconds"),
            "terminated_at": None,
            "ledger_entry_id": handle._ledger_entry_id,
            "work_dir": str(handle.work_dir),
            "upgrades": [],
        }

    def _on_provisioned(self, handle: ComputeHandle, *, phase_id: str) -> None:
        record = self._instance_record(handle, phase_id=phase_id, status="active")
        self._snapshot.setdefault("instances", {})[handle.machine.id] = record
        self._persist_snapshot()
        if self._emitter is not None:
            self._emitter.emit(
                "compute_provisioned",
                agent_id=f"phase:{phase_id}",
                parent_id="orchestrator",
                instance_id=record["instance_id"],
                instance_type=record["instance_type"],
                public_ip=record["public_ip"],
                hourly_rate_usd=record["hourly_rate_usd"],
                estimated_hours=record["estimated_hours"],
                estimated_cost_usd=record["estimated_cost_usd"],
                work_dir=record["work_dir"],
            )

    def _on_terminated(self, handle: ComputeHandle) -> None:
        instances = self._snapshot.setdefault("instances", {})
        record = instances.get(handle.machine.id)
        if record is None:
            return
        entry = self._ledger._entries.get(handle._ledger_entry_id)
        actual_hours = entry.actual_hours if entry else None
        actual_cost = entry.actual_cost() if entry else None
        record["status"] = "terminated"
        record["terminated_at"] = datetime.now().isoformat(timespec="seconds")
        if actual_hours is not None:
            record["actual_hours"] = actual_hours
        if actual_cost is not None:
            record["actual_cost_usd"] = actual_cost
        self._persist_snapshot()
        if self._emitter is not None:
            self._emitter.emit(
                "compute_terminated",
                agent_id=f"phase:{record.get('phase_id', 'unknown')}",
                parent_id="orchestrator",
                instance_id=record["instance_id"],
                actual_hours=record.get("actual_hours"),
                actual_cost_usd=record.get("actual_cost_usd"),
            )

    def _on_upgraded(
        self,
        old_instance_id: str,
        new_handle: ComputeHandle,
        *,
        phase_id: str,
        reason: str,
    ) -> None:
        instances = self._snapshot.setdefault("instances", {})
        old = instances.get(old_instance_id)
        if old is not None:
            old["status"] = "terminated"
            old["terminated_at"] = datetime.now().isoformat(timespec="seconds")
        new_record = self._instance_record(
            new_handle, phase_id=phase_id, status="active",
        )
        new_record["upgrades"].append({
            "from_instance_id": old_instance_id,
            "from_instance_type": old["instance_type"] if old else None,
            "reason": reason,
            "ts": new_record["provisioned_at"],
        })
        instances[new_handle.machine.id] = new_record
        self._persist_snapshot()
        if self._emitter is not None:
            self._emitter.emit(
                "compute_upgraded",
                agent_id=f"phase:{phase_id}",
                parent_id="orchestrator",
                from_instance_id=old_instance_id,
                to_instance_id=new_handle.machine.id,
                instance_type=new_record["instance_type"],
                public_ip=new_record["public_ip"],
                reason=reason,
            )


@dataclass
class PhaseEstimate:
    phase_id: str
    needs_gpu: bool
    instance_type: str
    hourly_rate_usd: float
    estimated_hours: float
    estimated_cost_usd: float


@dataclass
class RunEstimate:
    per_phase: list[PhaseEstimate]
    total_usd: float
    cap_usd: float

    def gpu_phases(self) -> list[PhaseEstimate]:
        return [p for p in self.per_phase if p.needs_gpu]


_JSON_RE = re.compile(r"\{.*?\}", re.DOTALL)


def _parse_decision(raw: str) -> CloudDecision:
    """Best-effort JSON extraction from a model response."""
    if not raw:
        return CloudDecision(False, DEFAULT_INSTANCE_TYPE, "empty response")
    match = _JSON_RE.search(raw)
    if match is None:
        return CloudDecision(False, DEFAULT_INSTANCE_TYPE, f"no JSON in response: {raw[:80]!r}")
    try:
        data = json.loads(match.group(0))
    except json.JSONDecodeError:
        return CloudDecision(False, DEFAULT_INSTANCE_TYPE, f"invalid JSON: {match.group(0)[:80]!r}")
    return CloudDecision(
        needs_gpu=bool(data.get("needs_gpu", False)),
        instance_type=str(data.get("instance_type") or DEFAULT_INSTANCE_TYPE),
        rationale=str(data.get("rationale", "")),
    )
